### ISSUE TITLE
update这里一直出错

### ISSUE THREAD

**Issue by c939984606** [Lancenas/actions-openwrt-helloworld#12]
Update feeds47s
##[error]Process completed with exit code 1.
Collecting package info: feeds/luci/modules/luci-mod-failsafe
Collecting package info: feeds/luci/modules/luci-mod-freifunk
Collecting package info: feeds/luci/modules/luci-mod-freifunk-community
Collecting package info: feeds/luci/modules/luci-mod-rpc
Collecting package info: feeds/luci/protocols/luci-proto-3g
Collecting package info: feeds/luci/protocols/luci-proto-ipip
Collecting package info: feeds/luci/protocols/luci-proto-ipv6
Collecting package info: feeds/luci/protocols/luci-proto-ncm
Collecting package info: feeds/luci/protocols/luci-proto-openconnect
Collecting package info: feeds/luci/protocols/luci-proto-ppp
Collecting package info: feeds/luci/protocols/luci-proto-qmi
Collecting package info: feeds/luci/protocols/luci-proto-relay
Collecting package info: feeds/luci/protocols/luci-proto-vpnc
Collecting package info: feeds/luci/protocols/luci-proto-wireguard
Collecting package info: feeds/luci/themes/luci-theme-bootstrap
Collecting package info: feeds/luci/themes/luci-theme-material
Collecting package info: merging...

Collecting package info: donefatal: Invalid revision range 97a4ffcc125611dd5f307d54570373832a73e62d..HEAD
fatal: Invalid revision range 97a4ffcc125611dd5f307d54570373832a73e62d..639f3631e80e9372e9791f5f93343f09241cdda6

Collecting target info: merging...

Collecting target info: doneUpdating feed 'routing' from 'https://git.openwrt.org/feed/routing.git;openwrt-19.07' ...
Cloning into './feeds/routing'...
fatal: unable to access 'https://git.openwrt.org/feed/routing.git/': Failed to connect to git.openwrt.org port 443: Connection timed out
failed.
##[error]Process completed with exit code 1.

**Comment by Lancenas** [comment]
试一试，没出现所述error。你的网络是不是有问题？
