### ISSUE TITLE
你这脚本有问题的,或者你这介绍有问题的

### ISSUE THREAD

**Issue by z826540272** [Lancenas/actions-openwrt-helloworld#13]
实际上到了ssh那一步再去看workflow的日志是点不开的,
必须要再那个页面ssh步骤之前就点开详细日志,到了ssh阶段才能看到ssh信息.
然而,说明中并没有注明要在SSH步骤之前打开详细日志.

**Comment by Lancenas** [comment]
日志随时可以查看，只是限制30分钟内可联。不能查看日志基本都是网络问题。

**Comment by z826540272** [comment]
> 日志随时可以查看，只是限制30分钟内可联。不能查看日志基本都是网络问题。

SSH之上的日志可以点开，ssh点不开。
你可以开个脚本等10分钟后再打开action测试一下能不能点开ssh信息

**Comment by dindom999** [comment]
我也遇到这个问题，到SSH就不动了，点不开小三角

**Comment by dindom999** [comment]
![图片](https://user-images.githubusercontent.com/5274818/80232112-f016ff00-8686-11ea-8d8b-f8bb1abbe510.png)

**Comment by Lancenas** [comment]
没问题呀！
![Xnip2020-04-25_11-21-30](https://user-images.githubusercontent.com/32763979/80270073-b0343400-86e7-11ea-8761-4d99bec6c380.png)
![Xnip2020-04-25_11-22-45](https://user-images.githubusercontent.com/32763979/80270075-b1fdf780-86e7-11ea-82f3-86407a1c333d.png)

**Comment by dindom999** [comment]
我感觉这不是脚本的问题，可能是虚拟机的BUG, tmate一直没有运行完，所以卡在那里不动了

**Comment by dindom999** [comment]
我看了 T3terx的源码后发现，问题出在网络连接上，改成全局F-gfw就成了
