### ISSUE TITLE
action过程出现报错，提示dev-lean-lede无法克隆

### ISSUE THREAD

**Issue by carlyang1986** [Lancenas/actions-openwrt-helloworld#15]
Clone source code0s
##[error]Process completed with exit code 128.
Run git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
Cloning into 'openwrt'...
warning: Could not find remote branch dev-lean-lede to clone.
fatal: Remote branch dev-lean-lede not found in upstream origin
##[error]Process completed with exit code 128.

**Comment by Lancenas** [comment]
Remote branch dev-lean-lede not found in upstream origin.

**Comment by carlyang1986** [comment]
What a pity, i found the app-passwall yestarday night. But it is removed today. I will try to git clone it in package/lean but i don't know how to solve its depends.
